apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: crud-spring
spec:
  selector:
    matchLabels:
      app: crud-spring
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: crud-spring
    spec:
      containers:
        - name: crud-spring
          image: fernandolomonaco/crud-spring:1.0 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
